[package]
name = "statistics-4you"
version = "0.1.0-dev"
edition = "2024"

[dependencies]
anyhow = "1"
const_format = "0.2"
env_logger = "0.11"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
